version: "3.9"

services:
  weaviate:
    platform: linux/amd64
    image: semitechnologies/weaviate:1.29.0
    container_name: fyp-project-weaviate
    ports:
      - "8081:8080"
      - "50051:50051"
    environment:
      - ENABLE_MODULES=text2vec-openai
      - ENABLE_GRPC=true
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate

      # Correct cluster config for single-node
      - CLUSTER_HOSTNAME=weaviate

    volumes:
      - ./weaviate_data:/var/lib/weaviate


  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - EMBEDDING_PROVIDER=openai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - weaviate
      - redis
    command: tail -f /dev/null

  redis:
    image: redis/redis-stack-server:latest
    container_name: fyp-project-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis_data:/data
